---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUXfcCH3w+8lhYz46vJNrnblmAwKswCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjIwNDE2MDQ0NDAwWhcNMzcwNDEyMDQ0NDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFX2
          JZWpGvrCzy7vSA3iS5t4vMdoBkClkZYm8b9+/ogq9FHqZB4tNmsWBPynu1siCc1A
          ++s59RbaBfCeE7xg2F2jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBR/A8/LP30A5AoL2TNrJq2Qn/9xuDAKBggqhkjOPQQD
          AgNIADBFAiEAkBrlZpzfZDAd8QujTvq7mUIisKzSwWmU9/2tYvLAweECIDuU0YrH
          6WyJvqxtVP+3AmWh2mdIrCldp1vupSvRc03D
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICJzCCAc2gAwIBAgIUXfcCH3w+8lhYz46vJNrnblmAwKswCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjIwNDE2MDQ0NDAwWhcNMzcwNDEyMDQ0NDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFX2
          JZWpGvrCzy7vSA3iS5t4vMdoBkClkZYm8b9+/ogq9FHqZB4tNmsWBPynu1siCc1A
          ++s59RbaBfCeE7xg2F2jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBR/A8/LP30A5AoL2TNrJq2Qn/9xuDAKBggqhkjOPQQD
          AgNIADBFAiEAkBrlZpzfZDAd8QujTvq7mUIisKzSwWmU9/2tYvLAweECIDuU0YrH
          6WyJvqxtVP+3AmWh2mdIrCldp1vupSvRc03D
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
