---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUJejPO+4+ZHRIQ6Y9MIfscread/IwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMjA0MTYwNDQ0MDBaFw0zNzA0MTIwNDQ0MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARmmvVt93Pp9Hoa
          +cIjyiH3WH1E5EOql18RK900q0zsDLXT1Hf277nk4AAyaO3MleluVuz2eUcyo0ob
          ZHuEXHEDo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUO5X3rihgKndlxVIHIUH0PAJE7D0wCgYIKoZIzj0EAwIDRwAwRAIg
          drONnEsZq1WZzV23S3AHgFWSeV7X3iw3kcXewlJcGMoCIFCZZBuIkTdD5fdlBNbD
          DzZo1JXQ+Q4tLVwupaUXUpgz
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUJejPO+4+ZHRIQ6Y9MIfscread/IwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yMjA0MTYwNDQ0MDBaFw0zNzA0MTIwNDQ0MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARmmvVt93Pp9Hoa
          +cIjyiH3WH1E5EOql18RK900q0zsDLXT1Hf277nk4AAyaO3MleluVuz2eUcyo0ob
          ZHuEXHEDo0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQUO5X3rihgKndlxVIHIUH0PAJE7D0wCgYIKoZIzj0EAwIDRwAwRAIg
          drONnEsZq1WZzV23S3AHgFWSeV7X3iw3kcXewlJcGMoCIFCZZBuIkTdD5fdlBNbD
          DzZo1JXQ+Q4tLVwupaUXUpgz
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
